name: Update README with Latest Medium Posts

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Fetch Latest Medium Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@jain.yash1909"


      - name: Commit Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add -A
          git commit -m 'Updated README with latest Medium posts' || echo "No changes to commit"
          git push
