name: Update README with Latest Medium Posts

on:
  schedule:
    - cron: '0 0 * 0 0'  # Runs once a week
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser requests beautifulsoup4

      - name: Fetch Medium Posts and Update README
        env:
          MEDIUM_USERNAME: "@jain.yash1909"
        run: python update_readme.py

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Updated README with latest Medium posts' || echo "No changes to commit"
          git push
