name: Generate Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Isocalendar Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      -name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.GITHUB_TOKEN  }}
          base: header, activity, community, repositories, metadata
      # - name: Generate Icons Metrics
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: metrics.plugin.topics.icons.svg
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     base: ""
      #     plugin_topics: yes
      #     plugin_topics_limit: 0
      #     plugin_topics_mode: icons
